### PR TITLE
Don't set `_USE_MATH_DEFINES` for MSVC as `qmath.h` does so.

### PR DESCRIPTION
**Pull request by dbrnz**
Setting it here can lead to macro redefinitions if `math.h` is included in the source file after `qwt_math.h`.

`QtCore/qglobal.h` (which is included by various Qt headers) has an include of `<algorithm>` that, under MSVC, includes `<cmath>`. When `qwt_math.h` is included later on in the source file, the include of `<cmath>` from `<qmath.h>` becomes a no-op and mathematical constants are defined by `<qmath>` instead of by `ucrt/corecrt_math_defines.h`. However if `_USE_MATH_DEFINES` is defined by `qwt_math.h` a later include of `<math.h>` (by say Python headers) will include `ucrt/corecrt_math_defines.h` and MSVC reports that macros have been redefined.

This issue (for Qt in general) is discussed in [QTBUG-45935](https://bugreports.qt.io/browse/QTBUG-45935).

### CODE REVIEW

**Comment by agarny** [comment]
That's fair enough. However, I wouldn't remove the code. Instead, I would comment it out as follows:

```
/*---OPENCOR---
#if defined(_MSC_VER)
*/
/*
  Microsoft says:

  Define _USE_MATH_DEFINES before including math.h to expose these macro
  definitions for common math constants.  These are placed under an #ifdef
  since these commonly-defined names are not part of the C/C++ standards.
*/
/*---OPENCOR---
#define _USE_MATH_DEFINES 1
#endif
*/
```

Indeed, this makes it easier/faster to compare different versions of Qwt (and this ensures that I won't re-add that piece of code by mistake next time round).

**Comment by agarny** [comment]
Oops, I didn't realise/know that I could edit your changes, so I have just done it and I am now going to merge your PR.

**Comment by dbrnz** [comment]
Thanks for merging this and cleaning things with `/*---OPENCOR---  */`.

Why not also just track upstream sources (as released on Sourceforge) on `master` and have a separate branch (say `opencor`) for our modifications? Then `git merge` could do most of the work when a new version is released.

**Comment by agarny** [comment]
> Why not also just track upstream sources (as released on Sourceforge) on `master` and have a separate branch (say `opencor`) for our modifications? Then `git merge` could do most of the work when a new version is released.

Good point, will try to think about it for the next version of Qwt.

**Pull request merged**
